<?php
/**
 * Installation-level configuration: database credentials and the app key.
 *
 * These values live in config/config.php (created by the setup wizard and
 * excluded from version control) rather than in the database, because the
 * database connection needs them before any query can run.
 */
declare(strict_types=1);

namespace StormWatch;

final class Config
{
    /** @var array<string,mixed> */
    private static array $values = [];

    private static bool $loaded = false;

    /** @var array<string,mixed> */
    private const DEFAULTS = [
        'db_driver'   => 'sqlite',
        'db_path'     => null,          // sqlite only; defaults to data/stormwatch.sqlite
        'db_host'     => '127.0.0.1',
        'db_port'     => 3306,
        'db_name'     => '',
        'db_user'     => '',
        'db_pass'     => '',
        'db_charset'  => 'utf8mb4',
        'app_key'     => '',            // base64:… 32 random bytes, encrypts stored secrets
        'base_url'    => '',            // e.g. https://example.com/stormwatch — used in Slack links
        'base_path'   => '',            // override the detected mount point, e.g. "/stormwatch"
        'trusted_proxy' => false,       // honour X-Forwarded-For when behind a proxy/CDN
    ];

    public static function load(): void
    {
        if (self::$loaded) {
            return;
        }
        self::$loaded = true;
        self::$values = self::DEFAULTS;

        if (is_file(SW_CONFIG_FILE)) {
            /** @var mixed $loaded */
            $loaded = require SW_CONFIG_FILE;
            if (is_array($loaded)) {
                self::$values = array_merge(self::$values, $loaded);
            }
        }

        if (empty(self::$values['db_path'])) {
            self::$values['db_path'] = SW_DATA . '/stormwatch.sqlite';
        }
    }

    public static function isInstalled(): bool
    {
        self::load();
        return is_file(SW_CONFIG_FILE) && self::$values['app_key'] !== '';
    }

    /**
     * Replace the loaded configuration for the rest of this process.
     *
     * Used by the test suite to point at a scratch database, and by anything
     * embedding the app that manages its own credentials. Writes nothing.
     *
     * @param array<string,mixed> $values
     */
    public static function override(array $values): void
    {
        self::load();
        self::$values = array_merge(self::$values, $values);
        self::$loaded = true;
    }

    /** @return mixed */
    public static function get(string $key, $default = null)
    {
        self::load();
        return self::$values[$key] ?? $default;
    }

    /** @return array<string,mixed> */
    public static function all(): array
    {
        self::load();
        return self::$values;
    }

    /**
     * Write config/config.php. Called by the setup wizard only.
     *
     * @param array<string,mixed> $values
     */
    public static function write(array $values): void
    {
        // The app key is what makes the stored Slack token and SMTP password
        // readable. Replacing an existing one turns both into noise that no
        // error message will explain, so a re-run keeps the key it finds.
        self::load();
        $existingKey = (string) (self::$values['app_key'] ?? '');
        if ($existingKey !== '' && (string) ($values['app_key'] ?? '') !== $existingKey) {
            $values['app_key'] = $existingKey;
        }

        $merged = array_merge(self::DEFAULTS, $values);
        unset($merged['db_path']); // keep the default data/ location portable across hosts

        $lines = [
            '<?php',
            '/**',
            ' * Storm Watch installation config — generated by the setup wizard.',
            ' * Keep this file out of version control and out of the web root.',
            ' */',
            'return [',
        ];
        foreach ($merged as $key => $value) {
            $lines[] = sprintf("    %-15s => %s,", var_export($key, true), var_export($value, true));
        }
        $lines[] = '];';
        $lines[] = '';

        $dir = dirname(SW_CONFIG_FILE);
        if (!is_dir($dir) && !@mkdir($dir, 0755, true) && !is_dir($dir)) {
            throw new \RuntimeException('Could not create the config directory: ' . $dir);
        }
        if (@file_put_contents(SW_CONFIG_FILE, implode("\n", $lines), LOCK_EX) === false) {
            throw new \RuntimeException('Could not write ' . SW_CONFIG_FILE . '. Check the file permissions.');
        }
        @chmod(SW_CONFIG_FILE, 0640);

        self::$loaded = false;
        self::load();
    }

    public static function generateAppKey(): string
    {
        return 'base64:' . base64_encode(random_bytes(32));
    }
}
